parameters:
#    main_feeds_reader.example.class: MainFeeds\ReaderBundle\Example

services:
#    main_feeds_reader.example:
#        class: %main_feeds_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]